// Regenerate src/schema.ts from the normative schema in the Python package.
// The JSON text is embedded verbatim so the exported constant is
// byte-identical in content to src/worldview_core/worldview-core.schema.json.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const source = path.resolve(here, "../../../src/worldview_core/worldview-core.schema.json");
const target = path.resolve(here, "../src/schema.ts");

const text = readFileSync(source, "utf8").replace(/\r\n/g, "\n").trimEnd();
JSON.parse(text); // fail loudly if the source is not valid JSON

const out = `// GENERATED by scripts/sync-schema.mjs from src/worldview_core/worldview-core.schema.json.
// Do not edit by hand; run \`npm run sync-schema\` after changing the schema.

import type { JsonObject } from "./model.js";

/**
 * The normative JSON Schema (draft 2020-12) for worldview-core files.
 * Identical in content to the schema shipped with the Python package.
 */
export const schema: JsonObject = ${text};
`;
writeFileSync(target, out, { encoding: "utf8" });
console.log(`wrote ${path.relative(process.cwd(), target)} from ${path.relative(process.cwd(), source)}`);
