// GENERATED by scripts/sync-schema.mjs from src/worldview_core/worldview-core.schema.json.
// Do not edit by hand; run `npm run sync-schema` after changing the schema.

import type { JsonObject } from "./model.js";

/**
 * The normative JSON Schema (draft 2020-12) for worldview-core files.
 * Identical in content to the schema shipped with the Python package.
 */
export const schema: JsonObject = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/stephenacomb/worldview_hypergraph/schema/worldview-core-0.1.schema.json",
  "title": "worldview-core",
  "description": "A worldview: natural-language statements connected by arguments, where an argument is a directed hyperedge from N premise statements to M conclusion statements. This schema is the normative definition of the file format. Referential integrity (every referenced id exists, ids unique within the file) is enforced by the validator, not by this schema.",
  "type": "object",
  "required": ["format", "version", "statements", "arguments"],
  "additionalProperties": false,
  "properties": {
    "format": {
      "const": "worldview-core",
      "description": "Format discriminator. Always the literal string \"worldview-core\"."
    },
    "version": {
      "type": "string",
      "pattern": "^[0-9]+\\.[0-9]+$",
      "description": "Format version as \"major.minor\". This library reads 0.x files."
    },
    "name": {
      "type": "string",
      "description": "Human-readable name of the worldview. Free text, not evaluative."
    },
    "description": {
      "type": "string",
      "description": "Free-text description of the worldview."
    },
    "meta": { "$ref": "#/$defs/meta" },
    "ext": { "$ref": "#/$defs/ext" },
    "statements": {
      "type": "array",
      "items": { "$ref": "#/$defs/statement" },
      "description": "The nodes of the hypergraph. Order is not meaningful."
    },
    "arguments": {
      "type": "array",
      "items": { "$ref": "#/$defs/argument" },
      "description": "The hyperedges of the hypergraph. Order is not meaningful."
    }
  },
  "$defs": {
    "id": {
      "type": "string",
      "minLength": 1,
      "pattern": "^\\S+$",
      "description": "A local identifier: any non-empty string without whitespace. Unique within its kind (statement or argument) in one file. Meaningful only inside this file; never used for cross-file identity."
    },
    "meta": {
      "type": "object",
      "description": "Free-form, unstructured notes for humans. Ignored by hashing and by every query. Put roles like \"axiom\" or \"observation\" here if you want them; the format defines no vocabulary."
    },
    "ext": {
      "type": "object",
      "description": "Namespaced slot for machine-readable extensions written by sister projects, e.g. {\"defeasible\": {...}, \"bayes\": {...}}. Each key is a namespace; the core validates only that the value is an object and ignores its contents in hashing and queries.",
      "additionalProperties": { "type": "object" }
    },
    "statement": {
      "type": "object",
      "required": ["id", "text", "mode"],
      "additionalProperties": false,
      "properties": {
        "id": { "$ref": "#/$defs/id" },
        "text": {
          "type": "string",
          "minLength": 1,
          "description": "The proposition, in natural language."
        },
        "mode": {
          "type": "string",
          "enum": ["is", "ought"],
          "description": "\"is\" for descriptive statements, \"ought\" for normative ones. Part of the statement's identity."
        },
        "meta": { "$ref": "#/$defs/meta" },
        "ext": { "$ref": "#/$defs/ext" }
      }
    },
    "argument": {
      "type": "object",
      "required": ["id", "premises", "conclusions", "justification"],
      "additionalProperties": false,
      "properties": {
        "id": { "$ref": "#/$defs/id" },
        "premises": {
          "type": "array",
          "items": { "$ref": "#/$defs/id" },
          "uniqueItems": true,
          "description": "Statement ids consumed jointly. May be empty. Order is not meaningful."
        },
        "conclusions": {
          "type": "array",
          "items": { "$ref": "#/$defs/id" },
          "minItems": 1,
          "uniqueItems": true,
          "description": "Statement ids asserted jointly by this argument. At least one. Order is not meaningful."
        },
        "justification": {
          "type": "string",
          "description": "Prose explaining why the conclusions follow from the premises. Part of the argument's identity."
        },
        "rule": {
          "type": "string",
          "description": "Optional name of the inference pattern, e.g. \"modus ponens\". Free text; no vocabulary is enforced. Not part of identity."
        },
        "meta": { "$ref": "#/$defs/meta" },
        "ext": { "$ref": "#/$defs/ext" }
      }
    }
  }
};
