/**
 * Replay every conformance vector against the TypeScript implementation.
 *
 * The vectors under conformance/vectors are generated by the Python
 * reference implementation (conformance/generate.py).  Every hash, every
 * query result, every diff bucket, every plan, lint, statistic, and merge
 * must match with deep equality: object key order is irrelevant, array
 * order is significant, and no property may be present-but-undefined
 * (toStrictEqual).  The Markdown of `present` and the DOT / Mermaid
 * exports are compared as exact strings.
 */

import { existsSync, readdirSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

import {
  H,
  ValidationError,
  canon,
  computeIdentities,
  diff,
  foundations,
  lintAll,
  merge,
  parseWorldview,
  plan,
  present,
  restsOn,
  sccs,
  statementIds,
  stats,
  supports,
  toDot,
  toMermaid,
  validateDict,
  wellFounded,
  worldviewFromDict,
} from "../src/index.js";
import type { HashPart, Worldview, WorldviewDocument } from "../src/index.js";
import { VECTORS, readJson } from "./paths.js";

interface CaseVector {
  name: string;
  input: WorldviewDocument;
  expected: {
    valid: true;
    ids: unknown;
    foundations: unknown;
    sccs: unknown;
    well_founded: unknown;
    rests_on: Record<string, unknown>;
    supports: Record<string, unknown>;
    rests_on_depth_1: Record<string, unknown>;
    supports_depth_1: Record<string, unknown>;
  };
}

interface InvalidVector {
  name: string;
  input: unknown;
  expected: { valid: false };
}

interface DiffVector {
  a: string;
  b: string;
  expected: unknown;
}

interface ExtrasVector {
  name: string;
  expected: {
    plan: Record<string, Array<{ given: string[]; result: unknown }>>;
    lint_all: unknown;
    stats: unknown;
    present: Record<string, { plain: string; depth_1: string; given: { given: string[]; markdown: string } }>;
    dot: string;
    dot_no_ids_tb: string;
    mermaid: string;
    mermaid_no_ids_tb: string;
  };
}

interface MergeVector {
  base: string;
  ours: string;
  theirs: string;
  expected: unknown;
}

interface Primitives {
  canon: Array<{ input: string; output: string }>;
  H: Array<{ parts: HashPart[]; output: string }>;
}

function files(sub: string): string[] {
  const dir = path.join(VECTORS, sub);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .sort()
    .map((f) => path.join(dir, f));
}

const primitivesFile = path.join(VECTORS, "primitives.json");
const caseFiles = files("cases");
const invalidFiles = files("invalid");
const diffFiles = files("diffs");
const extrasFiles = files("extras");
const mergeFiles = files("merges");

/** Every vector file that a test actually replayed; checked against the disk listing at the end. */
const replayed = new Set<string>();

function caseInput(name: string): WorldviewDocument {
  const v = readJson(path.join(VECTORS, "cases", `${name}.json`)) as CaseVector;
  return v.input;
}

describe("conformance vectors", () => {
  it("are present", () => {
    expect(existsSync(primitivesFile)).toBe(true);
    expect(caseFiles.length).toBeGreaterThan(0);
    expect(invalidFiles.length).toBeGreaterThan(0);
    expect(diffFiles.length).toBeGreaterThan(0);
    expect(extrasFiles.length).toBeGreaterThan(0);
    expect(mergeFiles.length).toBeGreaterThan(0);
  });

  describe("primitives", () => {
    const prims = readJson(primitivesFile) as Primitives;

    it.each(prims.canon.map((c, i) => [i, c] as const))("canon vector %i", (_i, c) => {
      replayed.add(primitivesFile);
      expect(canon(c.input)).toBe(c.output);
    });

    it.each(prims.H.map((h, i) => [i, h] as const))("H vector %i", (_i, h) => {
      replayed.add(primitivesFile);
      expect(H(...h.parts)).toBe(h.output);
    });
  });

  describe.each(caseFiles.map((f) => [path.basename(f, ".json"), f] as const))("case %s", (_name, file) => {
    const v = readJson(file) as CaseVector;
    const exp = v.expected;
    const wv = worldviewFromDict(v.input, v.name);

    it("is valid", () => {
      replayed.add(file);
      expect(validateDict(v.input)).toStrictEqual([]);
      expect(() => parseWorldview(v.input, v.name)).not.toThrow();
    });

    it("identities", () => {
      expect(computeIdentities(wv).toDict()).toStrictEqual(exp.ids);
    });

    it("foundations", () => {
      expect(foundations(wv)).toStrictEqual(exp.foundations);
    });

    it("sccs", () => {
      expect(sccs(wv)).toStrictEqual(exp.sccs);
    });

    it("well_founded", () => {
      expect(wellFounded(wv)).toStrictEqual(exp.well_founded);
    });

    it("rests_on (full depth)", () => {
      for (const [sid, want] of Object.entries(exp.rests_on)) {
        expect(restsOn(wv, sid), sid).toStrictEqual(want);
      }
    });

    it("supports (full depth)", () => {
      for (const [sid, want] of Object.entries(exp.supports)) {
        expect(supports(wv, sid), sid).toStrictEqual(want);
      }
    });

    it("rests_on (depth 1) for every statement", () => {
      for (const sid of statementIds(wv)) {
        expect(restsOn(wv, sid, 1), sid).toStrictEqual(exp.rests_on_depth_1[sid]);
      }
    });

    it("supports (depth 1) for every statement", () => {
      for (const sid of statementIds(wv)) {
        expect(supports(wv, sid, 1), sid).toStrictEqual(exp.supports_depth_1[sid]);
      }
    });

    it("query results survive a JSON round trip unchanged", () => {
      const ids = computeIdentities(wv).toDict();
      expect(JSON.parse(JSON.stringify(ids))).toStrictEqual(ids);
      for (const sid of statementIds(wv)) {
        const r = restsOn(wv, sid);
        expect(JSON.parse(JSON.stringify(r))).toStrictEqual(r);
      }
    });
  });

  describe.each(invalidFiles.map((f) => [path.basename(f, ".json"), f] as const))("invalid %s", (_name, file) => {
    it("is rejected", () => {
      replayed.add(file);
      const v = readJson(file) as InvalidVector;
      expect(v.expected.valid).toBe(false);
      const problems = validateDict(v.input);
      expect(problems.length).toBeGreaterThan(0);
      let thrown: unknown;
      try {
        parseWorldview(v.input);
      } catch (e) {
        thrown = e;
      }
      expect(thrown).toBeInstanceOf(ValidationError);
      expect((thrown as ValidationError).problems).toStrictEqual(problems);
    });
  });

  describe.each(diffFiles.map((f) => [path.basename(f, ".json"), f] as const))("diff %s", (_name, file) => {
    it("matches the expected buckets", () => {
      replayed.add(file);
      const v = readJson(file) as DiffVector;
      const wa = worldviewFromDict(caseInput(v.a), v.a);
      const wb = worldviewFromDict(caseInput(v.b), v.b);
      expect(diff(wa, wb)).toStrictEqual(v.expected);
    });
  });

  describe.each(extrasFiles.map((f) => [path.basename(f, ".json"), f] as const))("extras %s", (_name, file) => {
    const v = readJson(file) as ExtrasVector;
    const exp = v.expected;
    const wv = worldviewFromDict(caseInput(v.name), v.name);

    it("plan for several given sets", () => {
      replayed.add(file);
      for (const [sid, runs] of Object.entries(exp.plan)) {
        for (const run of runs) {
          expect(plan(wv, sid, run.given), `${sid} given ${JSON.stringify(run.given)}`).toStrictEqual(run.result);
        }
      }
    });

    it("lint_all", () => {
      expect(lintAll(wv)).toStrictEqual(exp.lint_all);
    });

    it("stats", () => {
      expect(stats(wv)).toStrictEqual(exp.stats);
    });

    it("present (plain, depth 1, given) is the same Markdown text", () => {
      for (const [sid, runs] of Object.entries(exp.present)) {
        expect(present(wv, sid), sid).toBe(runs.plain);
        expect(present(wv, sid, { depth: 1 }), sid).toBe(runs.depth_1);
        expect(present(wv, sid, { given: runs.given.given }), sid).toBe(runs.given.markdown);
      }
    });

    it("dot and mermaid exports are the same text", () => {
      expect(toDot(wv)).toBe(exp.dot);
      expect(toDot(wv, { ids: false, wrap: 20, rankdir: "TB" })).toBe(exp.dot_no_ids_tb);
      expect(toMermaid(wv)).toBe(exp.mermaid);
      expect(toMermaid(wv, { ids: false, wrap: 20, direction: "TB" })).toBe(exp.mermaid_no_ids_tb);
    });
  });

  describe.each(mergeFiles.map((f) => [path.basename(f, ".json"), f] as const))("merge %s", (_name, file) => {
    it("matches the expected merged document, conflicts, and summary", () => {
      replayed.add(file);
      const v = readJson(file) as MergeVector;
      const wvs = (["base", "ours", "theirs"] as const).map((role) => worldviewFromDict(caseInput(v[role]), v[role]));
      const result = merge(wvs[0] as Worldview, wvs[1] as Worldview, wvs[2] as Worldview);
      expect(result).toStrictEqual(v.expected);
      expect(JSON.parse(JSON.stringify(result))).toStrictEqual(v.expected);
    });
  });

  it("replayed every vector file on disk", () => {
    const onDisk = [primitivesFile, ...caseFiles, ...invalidFiles, ...diffFiles, ...extrasFiles, ...mergeFiles].sort();
    expect([...replayed].sort()).toStrictEqual(onDisk);
    // eslint-disable-next-line no-console
    console.log(
      `conformance: replayed ${onDisk.length} vector files ` +
        `(primitives 1, cases ${caseFiles.length}, invalid ${invalidFiles.length}, diffs ${diffFiles.length}, ` +
        `extras ${extrasFiles.length}, merges ${mergeFiles.length})`,
    );
  });
});
