/**
 * Replay every conformance vector against the TypeScript implementation.
 *
 * The vectors under conformance/vectors are generated by the Python
 * reference implementation (conformance/generate.py).  Every hash, every
 * query result, and every diff bucket must match with deep equality:
 * object key order is irrelevant, array order is significant, and no
 * property may be present-but-undefined (toStrictEqual).
 */

import { existsSync, readdirSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

import {
  H,
  ValidationError,
  canon,
  computeIdentities,
  diff,
  foundations,
  parseWorldview,
  restsOn,
  sccs,
  statementIds,
  supports,
  validateDict,
  wellFounded,
  worldviewFromDict,
} from "../src/index.js";
import type { HashPart, WorldviewDocument } from "../src/index.js";
import { VECTORS, readJson } from "./paths.js";

interface CaseVector {
  name: string;
  input: WorldviewDocument;
  expected: {
    valid: true;
    ids: unknown;
    foundations: unknown;
    sccs: unknown;
    well_founded: unknown;
    rests_on: Record<string, unknown>;
    supports: Record<string, unknown>;
    rests_on_depth_1: Record<string, unknown>;
    supports_depth_1: Record<string, unknown>;
  };
}

interface InvalidVector {
  name: string;
  input: unknown;
  expected: { valid: false };
}

interface DiffVector {
  a: string;
  b: string;
  expected: unknown;
}

interface Primitives {
  canon: Array<{ input: string; output: string }>;
  H: Array<{ parts: HashPart[]; output: string }>;
}

function files(sub: string): string[] {
  const dir = path.join(VECTORS, sub);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .sort()
    .map((f) => path.join(dir, f));
}

const primitivesFile = path.join(VECTORS, "primitives.json");
const caseFiles = files("cases");
const invalidFiles = files("invalid");
const diffFiles = files("diffs");

/** Every vector file that a test actually replayed; checked against the disk listing at the end. */
const replayed = new Set<string>();

function caseInput(name: string): WorldviewDocument {
  const v = readJson(path.join(VECTORS, "cases", `${name}.json`)) as CaseVector;
  return v.input;
}

describe("conformance vectors", () => {
  it("are present", () => {
    expect(existsSync(primitivesFile)).toBe(true);
    expect(caseFiles.length).toBeGreaterThan(0);
    expect(invalidFiles.length).toBeGreaterThan(0);
    expect(diffFiles.length).toBeGreaterThan(0);
  });

  describe("primitives", () => {
    const prims = readJson(primitivesFile) as Primitives;

    it.each(prims.canon.map((c, i) => [i, c] as const))("canon vector %i", (_i, c) => {
      replayed.add(primitivesFile);
      expect(canon(c.input)).toBe(c.output);
    });

    it.each(prims.H.map((h, i) => [i, h] as const))("H vector %i", (_i, h) => {
      replayed.add(primitivesFile);
      expect(H(...h.parts)).toBe(h.output);
    });
  });

  describe.each(caseFiles.map((f) => [path.basename(f, ".json"), f] as const))("case %s", (_name, file) => {
    const v = readJson(file) as CaseVector;
    const exp = v.expected;
    const wv = worldviewFromDict(v.input, v.name);

    it("is valid", () => {
      replayed.add(file);
      expect(validateDict(v.input)).toStrictEqual([]);
      expect(() => parseWorldview(v.input, v.name)).not.toThrow();
    });

    it("identities", () => {
      expect(computeIdentities(wv).toDict()).toStrictEqual(exp.ids);
    });

    it("foundations", () => {
      expect(foundations(wv)).toStrictEqual(exp.foundations);
    });

    it("sccs", () => {
      expect(sccs(wv)).toStrictEqual(exp.sccs);
    });

    it("well_founded", () => {
      expect(wellFounded(wv)).toStrictEqual(exp.well_founded);
    });

    it("rests_on (full depth)", () => {
      for (const [sid, want] of Object.entries(exp.rests_on)) {
        expect(restsOn(wv, sid), sid).toStrictEqual(want);
      }
    });

    it("supports (full depth)", () => {
      for (const [sid, want] of Object.entries(exp.supports)) {
        expect(supports(wv, sid), sid).toStrictEqual(want);
      }
    });

    it("rests_on (depth 1) for every statement", () => {
      for (const sid of statementIds(wv)) {
        expect(restsOn(wv, sid, 1), sid).toStrictEqual(exp.rests_on_depth_1[sid]);
      }
    });

    it("supports (depth 1) for every statement", () => {
      for (const sid of statementIds(wv)) {
        expect(supports(wv, sid, 1), sid).toStrictEqual(exp.supports_depth_1[sid]);
      }
    });

    it("query results survive a JSON round trip unchanged", () => {
      const ids = computeIdentities(wv).toDict();
      expect(JSON.parse(JSON.stringify(ids))).toStrictEqual(ids);
      for (const sid of statementIds(wv)) {
        const r = restsOn(wv, sid);
        expect(JSON.parse(JSON.stringify(r))).toStrictEqual(r);
      }
    });
  });

  describe.each(invalidFiles.map((f) => [path.basename(f, ".json"), f] as const))("invalid %s", (_name, file) => {
    it("is rejected", () => {
      replayed.add(file);
      const v = readJson(file) as InvalidVector;
      expect(v.expected.valid).toBe(false);
      const problems = validateDict(v.input);
      expect(problems.length).toBeGreaterThan(0);
      let thrown: unknown;
      try {
        parseWorldview(v.input);
      } catch (e) {
        thrown = e;
      }
      expect(thrown).toBeInstanceOf(ValidationError);
      expect((thrown as ValidationError).problems).toStrictEqual(problems);
    });
  });

  describe.each(diffFiles.map((f) => [path.basename(f, ".json"), f] as const))("diff %s", (_name, file) => {
    it("matches the expected buckets", () => {
      replayed.add(file);
      const v = readJson(file) as DiffVector;
      const wa = worldviewFromDict(caseInput(v.a), v.a);
      const wb = worldviewFromDict(caseInput(v.b), v.b);
      expect(diff(wa, wb)).toStrictEqual(v.expected);
    });
  });

  it("replayed every vector file on disk", () => {
    const onDisk = [primitivesFile, ...caseFiles, ...invalidFiles, ...diffFiles].sort();
    expect([...replayed].sort()).toStrictEqual(onDisk);
    // eslint-disable-next-line no-console
    console.log(
      `conformance: replayed ${onDisk.length} vector files ` +
        `(primitives 1, cases ${caseFiles.length}, invalid ${invalidFiles.length}, diffs ${diffFiles.length})`,
    );
  });
});
